### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [mattelgrandexx/backendProyectoFinal#12]
Buenas! como va? encontre algunos comentarios en el codigo,

<img width="378" alt="Captura de pantalla 2023-01-23 170054" src="https://user-images.githubusercontent.com/53904695/214386154-156bd784-caed-4c5b-8928-0ee23258d71b.png">

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by mattelgrandexx** [comment]
Borre los comentarios del backend!
