### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [mattelgrandexx/backendProyectoFinal#13]
Buenas! encontre algunos console.log que no deberian estar..

<img width="371" alt="Captura de pantalla 2023-01-23 165611" src="https://user-images.githubusercontent.com/53904695/214386505-8b0bd089-69f0-4211-ace7-e642fc6f4bde.png">

los console.log en los catch o en donde necesitemos mostrar un error a los usuario por consola, deberian ser console.error

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by mattelgrandexx** [comment]
Listo, borre console logs de todo el backend!
